//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProfilerIntro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public long Id { get; set; }
        public long ArtistId { get; set; }
        public long CollectionId { get; set; }
        public string Name { get; set; }
        public string CensoredName { get; set; }
        public string ViewUrl { get; set; }
        public string PreviewUrl { get; set; }
        public string WorkUrl60 { get; set; }
        public string WorkUrl100 { get; set; }
        public decimal TWDPrice { get; set; }
        public decimal USDPrice { get; set; }
        public string Explicitness { get; set; }
        public int DiscCount { get; set; }
        public int DiscNumber { get; set; }
        public int Count { get; set; }
        public int Number { get; set; }
        public long TimeMillis { get; set; }
        public long PrimaryGenreId { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Artist Artist { get; set; }
        public virtual Collection Collection { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
